---
- name: Deploy HAProxy
  hosts: haproxy
  become: true

  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present
        update_cache: true

    - name: Deploy HAProxy configuration
      copy:
        src: ../config/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: "0644"
        validate: "haproxy -c -f %s"
      notify: reload haproxy

    - name: Enable and start HAProxy
      systemd:
        name: haproxy
        enabled: true
        state: started
        daemon_reload: true

  handlers:
    - name: reload haproxy
      systemd:
        name: haproxy
        state: reloaded
