---
all:
  children:
    elasticsearch:
      hosts:
        elasticsearch-vm:
          ansible_host: # populated from terraform output
    kibana:
      hosts:
        kibana-vm:
          ansible_host: # populated from terraform output
    haproxy:
      hosts:
        haproxy-vm:
          ansible_host: # populated from terraform output
    consul:
      hosts:
        consul-vm:
          ansible_host: # populated from terraform output
    postgresql:
      hosts:
        postgresql-vm:
          ansible_host: # populated from terraform output
    mysql:
      hosts:
        mysql-vm:
          ansible_host: # populated from terraform output
